version: "3.7"
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password 
    networks:
      - backnet
    environment: 
      - MYSQL_DATABASE=example
      - MYSQL_PASSWORD=password
  
  app:
    build: app
    restart: always
    secrets:
      - db-password
    networks:
      - backnet
      - frontnet
  
  web:
    build: web
    restart: always
    ports:
      - 80:80
    networks:
      - frontnet
  
networks:
  backnet:
  frontnet:

secrets:
  db-password:
    file: db/password.txt